apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: my-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: location
            operator: In
            values: [ 'europe' ]
---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: my-cluster
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: my-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.27.10+k3s2
---
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: linux
    elemental:
      registration:
        emulate-tpm: true
        emulated-tpm-seed: -1
      install:
        reboot: true
        device-selector:
          - key: Name
            operator: In
            values:
            - /dev/sda
            - /dev/vda
            - /dev/nvme0
            - /dev/mmcblk0
        debug: true
      reset:
        debug: true
        enabled: true
        reset-persistent: true
        reset-oem: true
        poweroff: false
        reboot: true
  machineInventoryLabels:
    location: europe
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
