apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: upgrade-to-dev
  namespace: fleet-default
spec:
  osImage: frallan/elemental-teal:v1.1.5-7cf3afa
    #osImage: "registry.opensuse.org/isv/rancher/elemental/staging/teal53/15.4/rancher/elemental-teal/5.3:latest"
  clusterTargets:
    - clusterName: my-cluster
  # upgradeContainer:
  #   envs:
  #     - name: FORCE
  #       value: "true"
